# Generated by Django 6.0.2 on 2026-02-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimoine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrimoine',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patrimoine',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='patrimoines/'),
        ),
    ]
