# Generated by Django 5.0.2 on 2026-02-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_Pat_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimoine',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
