# Generated by Django 6.0.2 on 2026-02-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_Pat_App', '0003_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='signinattempt',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PasswordResetCode',
        ),
    ]
