# Generated by Django 5.0.2 on 2026-02-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_Pat_App', '0003_alter_patrimoine_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patrimoine',
            name='ville',
        ),
        migrations.AlterField(
            model_name='patrimoine',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
