# Generated by Django 6.0.2 on 2026-02-20 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gest_Pat_App', '0004_signinattempt_locked_delete_passwordresetcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signinattempt',
            name='locked',
        ),
    ]
