# Generated by Django 5.0.2 on 2026-02-20 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_Pat_App', '0004_remove_patrimoine_ville_alter_patrimoine_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrimoine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='patrimoine/'),
        ),
    ]
