# Generated by Django 6.0.2 on 2026-02-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_Pat_App', '0005_remove_signinattempt_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrimoine',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patrimoine',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
