# Generated by Django 6.0.2 on 2026-02-21 03:07

import django.db.models.deletion
import gest_Pat_App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_Pat_App', '0006_patrimoine_description_patrimoine_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patrimoine',
            name='ville',
        ),
        migrations.AddField(
            model_name='patrimoine',
            name='polygone',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patrimoine',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='patrimoine/'),
        ),
        migrations.CreateModel(
            name='ImagePatrimoine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_originale', models.ImageField(upload_to='patrimoines/original/', validators=[gest_Pat_App.models.validation_image])),
                ('image_hd', models.ImageField(blank=True, null=True, upload_to='patrimoines/hd/')),
                ('miniature', models.ImageField(blank=True, null=True, upload_to='patrimoines/mini/')),
                ('patrimoine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gest_Pat_App.patrimoine')),
            ],
        ),
    ]
