# Generated by Django 5.0.2 on 2026-02-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_Pat_App', '0006_imagepatrimoine'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrimoine',
            name='polygone',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagepatrimoine',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patrimoine',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
